#!/bin/bash

# npm run babel -- --plugins transform-react-jsx

mkdir bin

# flow transform
# npm run babel -- --presets flow index.js
npm run babel -- js/ -d bin

# babel ignores the levels cuz they're huge, copy them over:
# cp -r js/levels bin/

# clientside require
npm run browserify -- bin/index.js -o bin/bundle.js




